default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database:  <%= ENV['DATABASE_NAME'] %>_development

test:
  <<: *default
  database:  <%= ENV['DATABASE_NAME'] %>_test

production:
  <<: *default
  database:  <%= ENV['DATABASE_NAME'] %>_production
  username: <%= ENV["PROD_DATABASE_USERNAME"] %>
  password: <%= ENV["PROD_DATABASE_PASSWORD"] %>
